### PR TITLE
fix: repair main after the managed-allocation move landed under stale PRs

### PR DESCRIPTION
**Pull request by thymikee**
`main` is red, and has been since #2308. Every open PR fails Typecheck, Repo Guards, and Integration Tests because of it — this unblocks them.

## What broke

#2316 moved managed-device allocation into `@agent-device/managed-allocation`. #2308 was authored before that move and merged after it, so the daemon files it added still import pre-move sibling paths:

```
src/daemon/managed-device-allocation/lease-admission.ts(19,8): error TS2307:
  Cannot find module './record-validation.ts'
src/daemon/managed-device-allocation/lease-admission.ts(70,5): error TS2322:
  Type 'string | undefined' is not assignable to type 'string'
src/daemon/managed-device-allocation/__tests__/lease-admission.fixtures.ts(10,61): error TS2307:
  Cannot find module './fixtures.ts'
test/integration/provider-scenarios/managed-runtime-automation.fixtures.ts(17,8): error TS2307:
  Cannot find module '.../managed-device-allocation/__tests__/fixtures.ts'
```

A semantic conflict, so neither PR's own CI could have caught it.

## Repairs

- **`lease-admission.ts`** reaches `freezeLease` / `isValidLease` / `isRequestGeneration` / `isVerbatimId` through the package's `./record` surface, which now re-exports them. `record-validation.ts` stays package-internal.
- **`TS2322` needed no separate fix.** It was a consequence of the unresolved import: with the module resolved, `isVerbatimId` narrows `grant.identityIncarnationId` to `string` again.
- **`src/daemon/managed-device-allocation/__tests__/fixtures.ts`** comes back, stated in contract terms only. Both trees keeping their own test data is the shape #2316 already chose for `managed-device-allocator.fixtures.ts`, which exists identically at both the root and package.
- **`.fallowrc.json`** drops its `@agent-device/managed-allocation` `ignoreDependencies` entry. Its comment read "no root consumer yet … it lands after the package's move" — the root consumer has now landed.

## Also failing on main, independently

`scripts/__tests__/eager-closure-budgets.test.ts > no APPROVED_OVER_CEILING row is stale` fails on pristine `origin/main`. The merge-base now carries `packages/capture-kit/src/durable-capture/index.ts` (added with #2320), so nothing can read its approval row, and the table's own staleness rule fails it — the intended outcome, just never actioned. Row removed.

## Validation

Verified failing on pristine `origin/main` first (typecheck and the closure gate, in a clean worktree), then green here:

- `pnpm typecheck` — clean
- `pnpm test:unit` — 1207 files, 9057 passed
- `managed-request-admission` + `managed-runtime-automation` provider suites — 19 passed
- `pnpm lint`, `pnpm format:check`, `pnpm check:layering`, `pnpm check:fallow`, `pnpm check:freerange` — all green

### CODE REVIEW

**Comment by thymikee** [comment]
Looks good at 1e65590c. The import repair uses the public package surface, the restored fixtures stay test-only, and the obsolete gate exception is removed. All checks are green.
